import Head from 'next/head'
import ContNavbar from './Components/Home/ContNavbar'
import Footer from './Components/Home/Footer'
import Header from './Components/Home/Header'
import Joinus from './Components/Home/Joinus'
import Navbar from './Components/Home/Navbar'
import OurClub from './Components/Home/OurClub'
import Player from './Components/Home/Player'
import Socceracedamy from './Components/Home/Socceracedamy'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContNavbar />
      <Navbar />
      <Header />
      <Player />
      <OurClub />
      <Socceracedamy />
      <Joinus />
      <Footer />
    </div>
  )
}





